FROM node:12-alpine AS base
WORKDIR /usr/src/chewiebot/client
COPY package*.json ./
RUN yarn install
RUN yarn global add react-scripts


FROM base AS build
WORKDIR /usr/src/chewiebot/client
COPY . ./
RUN yarn build

FROM nginx:stable-alpine
COPY --from=build /usr/src/chewiebot/client/build /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/
EXPOSE 80
