# docker-compose.yml
version: "3"
volumes:
    chewiebot-db:
services:
    ui:
        image: magentafall/chewiebot:client-latest
        ports:
            - 80:80
        expose:
            - 80
        command: ["nginx", "-g", "daemon off;"]
    backend:
        image: magentafall/chewiebot:server-latest
        volumes:
            - chewiebot-db:/usr/src/chewiebot/server/dist/chewiebot.db
        environment:
            NODE_ENV: production
        command: ["pm2-runtime", "start.js"]
