# docker-compose.yml
version: "3"
volumes:
    node_modules:
    chewie-db:
    images:
services:
    ui:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - ./client/:/usr/src/chewiebot/client
            - "/usr/src/chewiebot/client/node_modules/"
        ports:
            - 3001:3000
        expose:
            - 3001
        environment:
            - WATCHPACK_POLLING=true
        command: ["yarn", "start"]
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ./server:/usr/src/chewiebot/server
            - chewie-db:/usr/src/chewiebot/server/db
            - images:/usr/src/chewiebot/server/images
            - "/usr/src/chewiebot/server/node_modules/"
        ports:
            - 8080:8080
        environment:
            NODE_ENV: development
        command: ["npm", "run", "start-debug"]
