# docker-compose.yml
version: "3"
volumes:
    node_modules:
services:
    ui:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - ./client/:/usr/src/chewiebot/client
            - "/usr/src/chewiebot/client/node_modules/"
        ports:
            - 3001:3000
        expose:
            - 3001
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: ["yarn", "start"]
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ./server:/usr/src/chewiebot/server
            - "/usr/src/chewiebot/server/node_modules/"
        environment:
            NODE_ENV: development
        command: ["pm2-dev", "ecosystem.config.json"]
