# docker-compose.yml
version: "3"
volumes:
    node_modules:
    dist:
services:
    ui:
        build: ./client
        volumes:
            - ./client/build:/usr/share/nginx/html
            - "/usr/src/chewiebot/client/node_modules/"
    server:
        build: ./server
        volumes:
            - ./server:/usr/src/chewiebot/server
            - "/usr/src/chewiebot/server/node_modules/"
        environment:
            NODE_ENV: development
        command: ["pm2-runtime", "start.js", "--watch", '--node-args="--inspect=0.0.0.0"']
