# docker-compose.yml
version: "3"
services:
    ui:
        depends_on:
            - backend
        container_name: "chewiebot-client"
        networks:
            - front
    backend:
        ports:
            - 8001:8001
            - 8080:8080
            - 9229:9229
        environment:
            PORT: 8080
            REDIS_URL: redis://redis-cache
        depends_on:
            - redis
        container_name: "chewiebot-server"
        networks:
            - front
            - back
    redis:
        image: "redis:7.0.10"
        container_name: "redis-cache"
        expose:
            - 6379
        networks:
            - back
        volumes:
            - redis-data:/redis
volumes:
    redis-data:
networks:
    front:
        driver: bridge
    back:
        driver: bridge
