# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-to-digitalocean:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2          
      -
        name: Copy docker-compose.yml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.sshHost }}
          username: ${{ secrets.sshUsername }}
          key: ${{ secrets.sshKey }}
          source: "docker-compose.yml,docker-compose.prod.yml"
          target: "/chewiebot"
      -  
        name: Docker pull and run
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.sshHost }}
          username: ${{ secrets.sshUsername }}
          key: ${{ secrets.sshKey }}
          script: |
            docker login --username ${{ secrets.dockerUsername }} --password ${{ secrets.dockerKey }}
            mkdir -p chewiebot
            cd chewiebot
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
