name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - 
      name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.dockerUsername }}
        password: ${{ secrets.dockerKey }}
    
    - name: Build Server Docker Image
      uses: docker/build-push-action@v1.1.1
      with:
        username: ${{ secrets.dockerUsername }}
        password: ${{ secrets.dockerKey }}
        push: true
        path: ./server
        file: ./server/Dockerfile
        tags: ${{ secrets.dockerUsername }}/chewiebot:server-latest

    - name: Build Client Docker Image
      uses: docker/build-push-action@v1.1.1
      with:
        username: ${{ secrets.dockerUsername }}
        password: ${{ secrets.dockerKey }}
        push: true
        path: ./client
        file: ./client/Dockerfile
        tags: ${{ secrets.dockerUsername }}/chewiebot:client-latest
