# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
        
      - name: Update config
        uses: microsoft/variable-substitution@v1
        with: 
          files: './server/src/config.json'
        env:  
          twitch.client_id: ${{ secrets.twitchClientId }}
          twitch.client_secret: ${{ secrets.twitchClientSecret }}
          twitch.redirect_uri: ${{ secrets.twitchRedirectUri }}
          twitch.username: ${{ secrets.twitchUsername }}
          twitch.oauth: ${{ secrets.twitchOauth }}
          youtube.api: ${{ secrets.youtubeApi }}
          secretKey: ${{ secrets.botSecretKey }}
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: SCP Files
        uses: easingthemes/ssh-deploy@v2.1.4
        with:
          remote_host: ${{ secrets.sshHost }}
          remote_user: ${{ secrets.sshUsername }}
          ssh_private_key: ${{ secrets.sshKey }}
          source: ""
          target: "chewiebot"
