# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Deploy
              # You may pin to the exact commit or the version.
              # uses: JimCronqvist/action-ssh@1c03e01b4ac39da814b45cfd2924c2df0ff1396f
              uses: JimCronqvist/action-ssh@0.1.1
              with:
                  # Kill the current server and delete the folder.
                  command: |
                      export TWITCH_CLIENT_ID="${{ secrets.twitchClientId }}"
                      export TWITCH_CLIENT_SECRET="${{ secrets.twitchClientSecret }}"
                      export TWITCH_REDIRECT_URI="${{ secrets.twitchRedirectUri }}"
                      export YOUTUBE_API="${{ secrets.youtubeApi }}"
                      cd chewiebot
                      git pull origin master
                      cd server
                      yarn setup-production
                      yarn build
                      pm2 restart chewiebot
                      
                  # Hostname or IP address of the remote server(s). Separate multiple servers with a blank space. Example: 'user@mydomain.com:22 user@otherdomain.com:2222'
                  hosts: ${{ secrets.sshUsername }}@${{ secrets.sshHost }}
                  # The private key (id_rsa) content for authenticating to the SSH server(s). Recommended to store it as a GitHub Secret.
                  privateKey: ${{ secrets.sshKey }}
                  # Used to view all environment variables in the logs, please note that this could expose sensitive data.
                  #debug: # optional
